### ISSUE TITLE
Should I copy `templates` to my own repo for the generation?

### ISSUE THREAD

**Issue by zzxwill** [double12gzh/gotest-template#1]
Should I copy folder `templates` to my own repo for the unit tests generation?

**Comment by double12gzh** [comment]
Not necessary. Just save `templates` dir to any path you like on your local machine. 
For me,  I put `templates` to my `$HOME/.gotest-template`. It can be used just like: 

```bash
$ cd mygoproject
$ gotests -template_dir $HOME/.gotest-template/templates -only ^funcFoo$ -exported -w ./where/the/funcFoo/located/xxx_test.go ./where/the/funcFoo/located/xxx.go
```

**Comment by zzxwill** [comment]
Got it, thanks:)
